### ISSUE TITLE
Workspace support

### ISSUE THREAD

**Issue by berkus** [japaric/cargo-project#5]
As described in https://github.com/rust-embedded/cargo-binutils/issues/41 cargo-project does not properly support projects consisting of workspaces with cargo projects in them.

Easy test:
```
$ cat Cargo.toml
[workspace]
members = ["foo"]
```

cargo-project will explode on this, even though it's a valid cargo configuration.
This blocks cargo-binutils usage in any complex OS project.

**Comment by japaric** [comment]
Seems to have been fixed by #7 included in cargo-project v0.2.3. Note that you'll need to rebuild your tools against the latest `cargo-project`.

**Comment by berkus** [comment]
Great, will check it out, thanks!

**Comment by berkus** [comment]
[The problem is still there.](https://github.com/rust-embedded/cargo-binutils/issues/41#issuecomment-556092473)

**Comment by dvc94ch** [comment]
@japaric this is awesome, was just looking to build something similar for my projects `cargo-flutter` and `cargo-ndk`. However the problem is that query should take an optional package argument.

**Comment by berkus** [comment]
I worked around it by doing crazy Makefile.toml layers which go inside workspace members and run cargo-binutils there, looks like this is the intended usage and no fixes are planned to improve usability, @dvc94ch
